# Generated by Django 4.2.7 on 2025-02-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectName', models.CharField(blank=True, max_length=150, null=True)),
                ('ProjectDescription', models.TextField(blank=True, null=True)),
                ('Active', models.BooleanField(blank=True, default=True, null=True)),
                ('CreatedOn', models.DateTimeField(auto_now=True, null=True)),
                ('UpdatedOn', models.DateTimeField(auto_now=True, null=True)),
                ('company_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
