# Generated by Django 4.2.7 on 2025-02-16 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmaster',
            name='CreatedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectCreatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectmaster',
            name='ProjectBA',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectBA', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectmaster',
            name='ProjectCoordinator',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectmaster',
            name='UpdatedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectUpdatedBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
