# Generated by Django 4.2.7 on 2025-02-16 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClientName', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('UpdatedOn', models.DateTimeField(auto_now=True, null=True)),
                ('company_code', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClientId', models.IntegerField(blank=True, null=True)),
                ('company_code', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('UpdatedOn', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('ProjectName', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientsideManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClientId', models.IntegerField(blank=True, null=True)),
                ('ManagerName', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('UpdatedOn', models.DateTimeField(auto_now=True, null=True)),
                ('company_code', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClientId', models.IntegerField(blank=True, null=True)),
                ('Project', models.IntegerField(blank=True, null=True)),
                ('Assign_To', models.IntegerField(blank=True, null=True)),
                ('Assign_By', models.IntegerField(blank=True, null=True)),
                ('TaskDescription', models.TextField(blank=True, null=True)),
                ('AddNote', models.TextField(blank=True, null=True)),
                ('TaskValidation', models.IntegerField(blank=True, null=True)),
                ('Bonus', models.BooleanField(default=False)),
                ('FilledBy', models.IntegerField(blank=True, null=True)),
                ('company_code', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreateClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClientId', models.IntegerField(blank=True, null=True)),
                ('SPOC_Person', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('UpdatedOn', models.DateTimeField(auto_now=True, null=True)),
                ('company_code', models.CharField(blank=True, max_length=100, null=True)),
                ('Client_ManagerId', models.ManyToManyField(blank=True, to='ClientMaster.clientsidemanager')),
                ('Team', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
