# Generated by Django 4.2.7 on 2025-02-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarryForwardedLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeId', models.CharField(blank=True, max_length=255, null=True)),
                ('LeaveTypeId', models.CharField(blank=True, max_length=255, null=True)),
                ('Year', models.CharField(blank=True, max_length=255, null=True)),
                ('LeaveCount', models.CharField(blank=True, max_length=255, null=True)),
                ('company_code', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveTypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeName', models.CharField(blank=True, max_length=255, null=True)),
                ('company_code', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
