# Generated by Django 4.2.7 on 2025-02-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leave', '0002_carryforwardedleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='carryforwardedleave',
            name='LeaveCount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
