# Generated by Django 4.2.7 on 2025-02-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=True)),
                ('period', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.BigIntegerField(blank=True, null=True)),
                ('amount', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='companyinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100, null=True)),
                ('companylogos', models.ImageField(blank=True, null=True, upload_to='companyImages', verbose_name='Company Photo')),
                ('gstcertificate', models.ImageField(blank=True, null=True, upload_to='gstcertificate', verbose_name='Company Gst certificate')),
                ('companyAddress', models.TextField(max_length=254, null=True)),
                ('companycode', models.CharField(blank=True, max_length=100, null=True)),
                ('gstNumber', models.CharField(blank=True, max_length=55, null=True)),
                ('adhaarNumber', models.CharField(blank=True, max_length=55, null=True)),
                ('panNumber', models.CharField(blank=True, max_length=55, null=True)),
                ('memberadmin', models.CharField(blank=True, max_length=55, null=True)),
                ('payment', models.CharField(blank=True, max_length=55, null=True)),
                ('period', models.CharField(blank=True, max_length=155, null=True)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('companyType', models.CharField(blank=True, max_length=155, null=True)),
                ('expirydate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=155, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('isactive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='companypaymentlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyId', models.IntegerField(blank=True, null=True)),
                ('planperiod', models.CharField(blank=True, max_length=156, null=True)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('expirydate', models.DateField(blank=True, null=True)),
                ('payment', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=True)),
                ('companyType', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='paymentslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('name', models.CharField(max_length=156)),
                ('amount', models.FloatField()),
                ('month', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('company_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
