# Generated by Django 4.2.7 on 2025-01-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntermediateTrackProResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Week', models.IntegerField(blank=True, null=True)),
                ('Year', models.IntegerField(blank=True, null=True)),
                ('TotalTask', models.IntegerField(blank=True, null=True)),
                ('Green', models.IntegerField(blank=True, null=True)),
                ('Yellow', models.IntegerField(blank=True, null=True)),
                ('Red', models.IntegerField(blank=True, null=True)),
                ('Bonus', models.IntegerField(blank=True, null=True)),
                ('Cancelled', models.IntegerField(blank=True, null=True)),
                ('Rejected', models.IntegerField(blank=True, null=True)),
                ('NotDone', models.IntegerField(blank=True, null=True)),
                ('Help', models.IntegerField(blank=True, null=True)),
                ('TrackProScore', models.IntegerField(blank=True, null=True)),
                ('TotalScore', models.IntegerField(blank=True, null=True)),
                ('TrackProPercent', models.FloatField(blank=True, null=True)),
                ('Rank', models.IntegerField(blank=True, null=True)),
                ('DepartmentwiseRank', models.IntegerField(blank=True, null=True)),
                ('company_code', models.CharField(blank=True, max_length=50, null=True)),
                ('extra_credit', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
