# Generated by Django 4.2.7 on 2025-01-31 07:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=50)),
                ('company_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('EndDate', models.DateTimeField(blank=True, null=True)),
                ('company_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatusName', models.CharField(max_length=25)),
                ('company_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssignByStr', models.CharField(blank=True, max_length=100, null=True)),
                ('AssignDate', models.DateField(blank=True, null=True)),
                ('Day', models.CharField(blank=True, default=5, max_length=10, null=True)),
                ('Week', models.IntegerField(default=5, null=True)),
                ('Year', models.IntegerField(blank=True, default=2025, null=True)),
                ('ProjectName', models.CharField(blank=True, max_length=1000, null=True)),
                ('TaskTitle', models.TextField(max_length=1000)),
                ('TaskDescription', models.CharField(max_length=500, null=True)),
                ('Bonus', models.BooleanField(default=False)),
                ('DueDateTime', models.DateField(null=True)),
                ('Active', models.BooleanField(default=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(auto_now=True, null=True)),
                ('company_code', models.CharField(blank=True, max_length=100, null=True)),
                ('AddedByManager', models.BooleanField(default=False)),
                ('ParentTaskId', models.IntegerField(blank=True, null=True)),
                ('IsParent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TaskPriorityMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PriorityName', models.CharField(max_length=25)),
                ('company_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('created_by_str', models.CharField(max_length=500, null=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('ismanager', models.BooleanField(default=False)),
                ('remark_comment', models.TextField()),
                ('user_id', models.BigIntegerField()),
                ('user_str', models.CharField(max_length=500, null=True)),
                ('task_id', models.BigIntegerField(null=True)),
                ('Active', models.BooleanField(default=True)),
                ('IsRead', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ZoneName', models.CharField(max_length=25)),
                ('company_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NotificationTitle', models.CharField(max_length=51)),
                ('NotificationMsg', models.CharField(max_length=500, null=True)),
                ('ReadMsg', models.BooleanField(default=False)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('company_code', models.CharField(blank=True, max_length=50, null=True)),
                ('leaveID', models.IntegerField(blank=True, default=0, null=True)),
                ('To_manager', models.BooleanField(blank=True, default=False, null=True)),
                ('action_Taken', models.BooleanField(blank=True, default=False, null=True)),
                ('NotificationTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tasks.notificationtypemaster')),
            ],
        ),
    ]
