# Generated by Django 4.2.7 on 2024-08-03 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tasks', '0001_initial'),
        ('Project', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasknotification',
            name='UserID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskmaster',
            name='AssignBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskassignby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskmaster',
            name='AssignTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskassignto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskmaster',
            name='CheckedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskcheckedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskmaster',
            name='CreatedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskcreatedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskmaster',
            name='HelpTaken',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='helptaken', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskmaster',
            name='LoggedUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loggeduser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskmaster',
            name='Project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_id', to='Project.projectmaster'),
        ),
        migrations.AddField(
            model_name='taskmaster',
            name='ReCheckedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskrecheckedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskmaster',
            name='Status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks.status'),
        ),
        migrations.AddField(
            model_name='taskmaster',
            name='TaskPriority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks.taskprioritymaster'),
        ),
        migrations.AddField(
            model_name='taskmaster',
            name='UpdatedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskupdatedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskmaster',
            name='Zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks.zone'),
        ),
        migrations.AddField(
            model_name='projecttasks',
            name='ParentTask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_task', to='Tasks.taskmaster'),
        ),
        migrations.AddField(
            model_name='projecttasks',
            name='Task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Tasks.taskmaster'),
        ),
    ]
