# Generated by Django 4.2.7 on 2024-08-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmaster',
            name='Day',
            field=models.CharField(blank=True, default=1, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='taskmaster',
            name='Week',
            field=models.IntegerField(default=32, null=True),
        ),
    ]
