# Generated by Django 4.2.7 on 2024-08-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_alter_taskmaster_day_alter_taskmaster_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmaster',
            name='Day',
            field=models.CharField(blank=True, default=3, max_length=10, null=True),
        ),
    ]
