# Generated by Django 4.2.7 on 2024-08-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0004_alter_taskmaster_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmaster',
            name='Week',
            field=models.IntegerField(default=33, null=True),
        ),
    ]
