# Generated by Django 4.2.7 on 2024-08-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0005_alter_taskmaster_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmaster',
            name='Day',
            field=models.CharField(blank=True, default=1, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='taskmaster',
            name='Week',
            field=models.IntegerField(default=34, null=True),
        ),
    ]
