# Generated by Django 4.2.7 on 2024-08-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0007_alter_taskmaster_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmaster',
            name='Week',
            field=models.IntegerField(default=35, null=True),
        ),
    ]
