# Generated by Django 4.2.7 on 2025-02-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0009_alter_taskmaster_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmaster',
            name='Day',
            field=models.CharField(blank=True, default=4, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='taskmaster',
            name='Week',
            field=models.IntegerField(default=6, null=True),
        ),
        migrations.AlterField(
            model_name='taskmaster',
            name='Year',
            field=models.IntegerField(blank=True, default=2025, null=True),
        ),
    ]
