# Generated by Django 4.2.7 on 2025-02-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0010_alter_taskmaster_day_alter_taskmaster_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmaster',
            name='Day',
            field=models.CharField(blank=True, default=5, max_length=10, null=True),
        ),
    ]
