# Generated by Django 4.2.7 on 2025-02-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0011_alter_taskmaster_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmaster',
            name='Day',
            field=models.CharField(blank=True, default=6, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='taskmaster',
            name='Week',
            field=models.IntegerField(default=7, null=True),
        ),
    ]
