# Generated by Django 4.2.7 on 2025-02-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PacketEmployeeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PacketId', models.CharField(blank=True, max_length=255, null=True)),
                ('EmployeeId', models.CharField(blank=True, max_length=255, null=True)),
                ('company_code', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PacketLeaveRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PacketId', models.CharField(blank=True, max_length=255, null=True)),
                ('company_code', models.CharField(blank=True, max_length=50, null=True)),
                ('LeaveTypeId', models.CharField(blank=True, max_length=255, null=True)),
                ('Rule1', models.BooleanField(default=False)),
                ('LeaveCount', models.CharField(blank=True, max_length=255, null=True)),
                ('LeaveCarryForwardCount', models.CharField(blank=True, max_length=255, null=True)),
                ('Rule2', models.BooleanField(default=False)),
                ('ApplicableEmployements', models.CharField(blank=True, max_length=255, null=True)),
                ('Rule3', models.BooleanField(default=False)),
                ('WPOLHoliday', models.BooleanField(blank=True, default=False, null=True)),
                ('PSHoliday', models.BooleanField(blank=True, default=False, null=True)),
                ('HAtLeastNoDays', models.CharField(blank=True, max_length=255, null=True)),
                ('WPOLWeeklyOff', models.BooleanField(blank=True, default=False, null=True)),
                ('PSWeeklyOff', models.BooleanField(blank=True, default=False, null=True)),
                ('WOAtLeastNoDays', models.CharField(blank=True, max_length=255, null=True)),
                ('Rule4', models.BooleanField(default=False)),
                ('ApprovalLevels', models.CharField(blank=True, max_length=255, null=True)),
                ('RejectionLevels', models.CharField(blank=True, default='1', max_length=255, null=True)),
                ('IfNoAction', models.CharField(blank=True, max_length=255, null=True)),
                ('IfNoActionBefore', models.CharField(blank=True, max_length=255, null=True)),
                ('IfNoActionFrom', models.CharField(blank=True, max_length=255, null=True)),
                ('Rule5', models.BooleanField(default=False)),
                ('ApplyUptoFuture', models.CharField(blank=True, max_length=255, null=True)),
                ('Rule6', models.BooleanField(default=False)),
                ('ApplyUptoPast', models.CharField(blank=True, max_length=255, null=True)),
                ('Rule7', models.BooleanField(default=False)),
                ('ApplyBefore', models.CharField(blank=True, max_length=255, null=True)),
                ('Rule8', models.BooleanField(default=False)),
                ('LeaveLongerThan', models.CharField(blank=True, max_length=255, null=True)),
                ('AttachmentRequired', models.BooleanField(blank=True, default=False, null=True)),
                ('Rule9', models.BooleanField(default=False)),
                ('WeeklyOffConsider', models.CharField(blank=True, max_length=255, null=True)),
                ('IfWeeklyOff6', models.BooleanField(blank=True, default=False, null=True)),
                ('WeeklyOffPattern', models.CharField(blank=True, max_length=255, null=True)),
                ('Rule10', models.BooleanField(default=False)),
                ('ProRatedCalculation', models.CharField(blank=True, max_length=255, null=True)),
                ('Rule11', models.BooleanField(default=False)),
                ('AutoEncashmentBeyond', models.CharField(blank=True, max_length=255, null=True)),
                ('Rule12', models.BooleanField(default=False)),
                ('EncashmentType', models.CharField(blank=True, max_length=255, null=True)),
                ('EncashmentApplyCount', models.CharField(blank=True, max_length=255, null=True)),
                ('MinEncashmentDays', models.CharField(blank=True, max_length=255, null=True)),
                ('MaxEncashmentDays', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PacketMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PacketName', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
