# Generated by Django 4.2.7 on 2025-01-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnounceMent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcementText', models.TextField(default=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('CreatedBy', models.CharField(blank=True, max_length=50, null=True)),
                ('CreatedOn', models.DateTimeField(auto_now=True, null=True)),
                ('company_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendancerule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fulldayhrs', models.CharField(blank=True, max_length=50, null=True)),
                ('Halfdayhrs', models.CharField(blank=True, max_length=50, null=True)),
                ('In_timehrs', models.CharField(blank=True, max_length=50, null=True)),
                ('time_extension', models.CharField(blank=True, max_length=50, null=True)),
                ('leverages', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('CreatedBy', models.CharField(blank=True, max_length=50, null=True)),
                ('CreatedOn', models.DateTimeField(auto_now=True, null=True)),
                ('company_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leaverule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Periodof_L', models.CharField(blank=True, max_length=50, null=True)),
                ('Assignedleaves', models.IntegerField(blank=True, null=True)),
                ('maxleaves', models.IntegerField(blank=True, null=True)),
                ('lapsestatus', models.CharField(max_length=50)),
                ('carryforward', models.FloatField(blank=True, max_length=50, null=True)),
                ('encashment', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('CreatedBy', models.CharField(blank=True, max_length=50, null=True)),
                ('CreatedOn', models.DateTimeField(auto_now=True, null=True)),
                ('company_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsText', models.TextField(default=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('CreatedBy', models.CharField(blank=True, max_length=50, null=True)),
                ('CreatedOn', models.DateTimeField(auto_now=True, null=True)),
                ('company_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ruleswar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('points', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('CreatedBy', models.CharField(blank=True, max_length=50, null=True)),
                ('CreatedOn', models.DateTimeField(auto_now=True, null=True)),
                ('company_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
