# Generated by Django 4.2.7 on 2025-02-14 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rules', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ruleswar',
            new_name='rulestrackpro',
        ),
    ]
