from django.db import models

# Create your models here.
class Section(models.Model):
    Name = models.CharField(max_length=50,null=True, blank=True)
    Description = models.CharField(max_length=200,null=True, blank=True)
    Tentative_limit = models.CharField(max_length=50,null=True, blank=True)
    Visibility = models.BooleanField(default=True,null=True)
    Is_Active = models.BooleanField(default=True,null=True)
    CreatedBy = models.CharField(max_length=50,null=True,blank=True)
    CreatedOn = models.DateTimeField(auto_now=True, null=True, blank=True)
    UpdatedBy = models.CharField(max_length=50,null=True,blank=True)
    UpdatedOn = models.DateTimeField(auto_now=True, null=True, blank=True)
    company_code = models.CharField(max_length=50,null=True, blank=True)

    def __str__(self):
        return str(self.Name)

class Section_Audit(models.Model):
    Name = models.CharField(max_length=50,null=True, blank=True)
    Description = models.CharField(max_length=200,null=True, blank=True)
    Tentative_limit = models.CharField(max_length=50,null=True, blank=True)
    Visibility = models.BooleanField(default=True,null=True)
    Is_Active = models.BooleanField(default=True,null=True)
    CreatedBy = models.CharField(max_length=50,null=True,blank=True)
    CreatedOn = models.DateTimeField(auto_now=True, null=True, blank=True)
    UpdatedBy = models.CharField(max_length=50,null=True,blank=True)
    UpdatedOn = models.DateTimeField(auto_now=True, null=True, blank=True)
    company_code = models.CharField(max_length=50,null=True, blank=True)


class InvestmentType(models.Model):
    sectionId = models.ForeignKey(Section, on_delete=models.CASCADE,null=True, blank=True)
    Name = models.CharField(max_length=50,null=True, blank=True)
    Description = models.CharField(max_length=200,null=True, blank=True)
    Max_limit = models.CharField(max_length=50,null=True, blank=True)
    Is_Active = models.BooleanField(default=True,null=True)
    CreatedBy = models.CharField(max_length=50,null=True,blank=True)
    CreatedOn = models.DateTimeField(auto_now=True, null=True, blank=True)
    UpdatedBy = models.CharField(max_length=50,null=True,blank=True)
    UpdatedOn = models.DateTimeField(auto_now=True, null=True, blank=True)
    ProofRequired = models.BooleanField(default=False,null=True,blank=True)
    Exemption_Limit = models.CharField(max_length=256,null=True,blank=True)
    DocRequired = models.CharField(max_length=256,null=True,blank=True)
    InvestmentSingleBatch = models.BooleanField(default=False,null=True,blank=True)
    SortOrder = models.CharField(max_length=256,null=True,blank=True)
    Invest_TypeCode =  models.CharField(max_length=256,null=True,blank=True)
    ExemptSection =  models.CharField(max_length=256,null=True,blank=True)
    No_Projection =  models.BooleanField(default=False,null=True,blank=True)
    Section =  models.CharField(max_length=256,null=True,blank=True)
    HideOnDeclaration =  models.BooleanField(default=False,null=True,blank=True)
    NewTaxRegimeApp =  models.CharField(max_length=256,null=True,blank=True)
    LTA_slabApplicable = models.BooleanField(default=False,null=True,blank=True)
    company_code = models.CharField(max_length=50,null=True, blank=True)



    def __str__(self):
        return str(self.Name)

class InvestmentTypeAudit(models.Model):
    sectionId = models.ForeignKey(Section, on_delete=models.CASCADE,null=True, blank=True)
    Name = models.CharField(max_length=50,null=True, blank=True)
    Description = models.CharField(max_length=200,null=True, blank=True)
    Max_limit = models.CharField(max_length=50,null=True, blank=True)
    Is_Active = models.BooleanField(default=True,null=True)
    CreatedBy = models.CharField(max_length=50,null=True,blank=True)
    CreatedOn = models.DateTimeField(auto_now=True, null=True, blank=True)
    UpdatedBy = models.CharField(max_length=50,null=True,blank=True)
    UpdatedOn = models.DateTimeField(auto_now=True, null=True, blank=True)
    ProofRequired = models.CharField(max_length=50,null=True,blank=True)
    Exemption_Limit = models.CharField(max_length=256,null=True,blank=True)
    DocRequired = models.CharField(max_length=256,null=True,blank=True)
    InvestmentSingleBatch = models.CharField(max_length=50,null=True,blank=True)
    SortOrder = models.CharField(max_length=256,null=True,blank=True)
    Invest_TypeCode =  models.CharField(max_length=256,null=True,blank=True)
    ExemptSection =  models.CharField(max_length=256,null=True,blank=True)
    No_Projection =  models.CharField(max_length=50,null=True,blank=True)
    Section =  models.CharField(max_length=256,null=True,blank=True)
    HideOnDeclaration =  models.CharField(max_length=50,null=True,blank=True)
    NewTaxRegimeApp =  models.CharField(max_length=256,null=True,blank=True)
    LTA_slabApplicable = models.CharField(max_length=50,null=True,blank=True)
    company_code = models.CharField(max_length=50,null=True, blank=True)



class InvestmentTypeOptions(models.Model):
    InvestmentTypeId = models.ForeignKey(InvestmentType, on_delete=models.CASCADE,null=True, blank=True)
    optionNo = models.BigIntegerField(null=True,blank=True)
    optionText = models.CharField(max_length=256,null=True, blank=True)
    optionValue = models.BigIntegerField(null=True,blank=True)
    company_code =  models.CharField(max_length=50,null=True, blank=True)

class InvestmentDisease(models.Model):
    DiseaseName = models.CharField(max_length=256,null=True, blank=True)
    CreatedBy = models.CharField(max_length=50,null=True,blank=True)
    CreatedOn = models.DateTimeField(auto_now=True, null=True, blank=True)
    UpdatedBy = models.CharField(max_length=50,null=True,blank=True)
    UpdatedOn = models.DateTimeField(auto_now=True, null=True, blank=True)
    company_code =  models.CharField(max_length=50,null=True, blank=True)
    Is_Active = models.BooleanField(default=True,null=True)

class InvestmentFinancialYear(models.Model):
    FinancialYear = models.CharField(max_length=50,null=True,blank=True)
    Is_Active = models.BooleanField(default=True,null=True)
    FinancialShort =  models.CharField(max_length=50,null=True,blank=True)
    company_code =  models.CharField(max_length=50,null=True, blank=True)
    CreatedBy = models.CharField(max_length=50,null=True,blank=True)
    CreatedOn = models.DateTimeField(auto_now=True, null=True, blank=True)
    UpdatedBy = models.CharField(max_length=50,null=True,blank=True)
    UpdatedOn = models.DateTimeField(auto_now=True, null=True, blank=True)

    def __str__(self):
        return str(self.FinancialYear)


class Investment_LTAFinYearSlab(models.Model):
    FinancialYear = models.CharField(max_length=50,null=True,blank=True)
    slab = models.FloatField(null=True,blank=True)
    CreatedBy = models.CharField(max_length=50,null=True,blank=True)
    CreatedOn = models.DateTimeField(auto_now=True, null=True, blank=True)
    UpdatedBy = models.CharField(max_length=50,null=True,blank=True)
    UpdatedOn = models.DateTimeField(auto_now=True, null=True, blank=True)
    company_code =  models.CharField(max_length=50,null=True, blank=True)

class Investment_OnOff(models.Model):
    start_date =  models.DateField(null=True)
    end_date = models.DateField(null=True)
    dtype = models.IntegerField(null=True,blank=True)
    message =  models.CharField(max_length=256,null=True,blank=True)
    EmployeeCode = models.CharField(max_length=100,null=True,blank=True)
    CreatedBy = models.CharField(max_length=50,null=True,blank=True)
    CreatedOn = models.DateTimeField(auto_now=True, null=True, blank=True)
    UpdatedBy = models.CharField(max_length=50,null=True,blank=True)
    UpdatedOn = models.DateTimeField(auto_now=True, null=True, blank=True)
    company_code =  models.CharField(max_length=50,null=True, blank=True)

class InvestmentPayrollConfig(models.Model):
    Payroll_On_Declared =  models.CharField(max_length=100,null=True,blank=True)
    Payroll_On_Proof =  models.CharField(max_length=100,null=True,blank=True)
    CreatedBy = models.CharField(max_length=50,null=True,blank=True)
    CreatedOn = models.DateTimeField(auto_now=True, null=True, blank=True)
    FinancialYearId =  models.ForeignKey(InvestmentFinancialYear, on_delete=models.CASCADE,null=True, blank=True)
    company_code =  models.CharField(max_length=50,null=True, blank=True)

class InvestmentPayrollConfig_Employee(models.Model):
    EmployeeCode = models.CharField(max_length=100,null=True,blank=True)
    Payroll_On_Declared =  models.CharField(max_length=100,null=True,blank=True)
    Payroll_On_Proof =  models.CharField(max_length=100,null=True,blank=True)
    CreatedBy = models.CharField(max_length=50,null=True,blank=True)
    CreatedOn = models.DateTimeField(auto_now=True, null=True, blank=True)
    FinancialYearId =  models.ForeignKey(InvestmentFinancialYear, on_delete=models.CASCADE,null=True, blank=True)
    company_code =  models.CharField(max_length=50,null=True, blank=True)


class InvestmentMembers(models.Model):
    MemberName =  models.CharField(max_length=100,null=True,blank=True)
    MemberPass = models.CharField(max_length=100,null=True,blank=True)
    MemberEmail = models.EmailField(verbose_name='email', max_length=60, unique=True)
    memberMobileNo =  models.CharField(max_length=10,null=True, blank=True )
    MemberPhoto =  models.ImageField(upload_to='InvestmentImages/', blank=True, null=True,verbose_name='Member Photo')
    Is_Active = models.BooleanField(default=True,null=True)
    BatchCount = models.IntegerField(null=True,blank=True)
    FileCount = models.IntegerField(null=True,blank=True)
    MemberCode = models.CharField(max_length=100,null=True,blank=True)
    AttributeTypeId  = models.CharField(max_length=100,null=True, blank=True )
    AttributeTypeDescription = models.TextField(null=True, blank=True )
    AttributeTypeUnitId = models.CharField(max_length=100,null=True, blank=True )
    AttributeTypeUnitDescription = models.TextField(null=True, blank=True )
    company_code =  models.CharField(max_length=50,null=True, blank=True)
    CreatedBy = models.CharField(max_length=50,null=True,blank=True)
    CreatedOn = models.DateTimeField(auto_now=True, null=True, blank=True)
    UpdatedBy = models.CharField(max_length=50,null=True,blank=True)
    UpdatedOn = models.DateTimeField(auto_now=True, null=True, blank=True)

class InvestmentMembersAudit(models.Model):
    MemberName =  models.CharField(max_length=100,null=True,blank=True)
    MemberPass = models.CharField(max_length=100,null=True,blank=True)
    MemberEmail = models.EmailField(verbose_name='email', max_length=60, unique=True)
    memberMobileNo =  models.CharField(max_length=10,null=True, blank=True )
    MemberPhoto =  models.ImageField(upload_to='InvestmentImages/', blank=True, null=True,verbose_name='Member Photo')
    Is_Active = models.BooleanField(default=True,null=True)
    BatchCount = models.IntegerField(null=True,blank=True)
    FileCount = models.IntegerField(null=True,blank=True)
    MemberCode = models.CharField(max_length=100,null=True,blank=True)
    AttributeTypeId  = models.CharField(max_length=100,null=True, blank=True )
    AttributeTypeDescription = models.TextField(null=True, blank=True )
    AttributeTypeUnitId = models.CharField(max_length=100,null=True, blank=True )
    AttributeTypeUnitDescription = models.TextField(null=True, blank=True )
    company_code =  models.CharField(max_length=50,null=True, blank=True)
    CreatedBy = models.CharField(max_length=50,null=True,blank=True)
    CreatedOn = models.DateTimeField(auto_now=True, null=True, blank=True)
    UpdatedBy = models.CharField(max_length=50,null=True,blank=True)
    UpdatedOn = models.DateTimeField(auto_now=True, null=True, blank=True)


class InvestmentReasons(models.Model):
    ReasonName = models.CharField(max_length=100,null=True, blank=True )
    ReasonDescription = models.TextField(null=True, blank=True )
    company_code =  models.CharField(max_length=50,null=True, blank=True)
    CreatedBy = models.CharField(max_length=50,null=True,blank=True)
    CreatedOn = models.DateTimeField(auto_now=True, null=True, blank=True)
    UpdatedBy = models.CharField(max_length=50,null=True,blank=True)
    UpdatedOn = models.DateTimeField(auto_now=True, null=True, blank=True)
    Is_Active = models.BooleanField(default=True,null=True)


class InvestmentStatusMaster(models.Model):
    StatusName = models.CharField(max_length=100,null=True, blank=True )
    StatusDescription = models.TextField(null=True, blank=True)
    StatusColorCode =  models.CharField(max_length=100,null=True, blank=True )
    StatusIconPath =  models.CharField(max_length=100,null=True, blank=True )
    StatusOrder = models.IntegerField(null=True,blank=True)
    CreatedBy = models.CharField(max_length=50,null=True,blank=True)
    CreatedOn = models.DateTimeField(auto_now=True, null=True, blank=True)
    Is_Active = models.BooleanField(default=True,null=True)
    Email =  models.EmailField(verbose_name='email', max_length=60, unique=True)
    SMS = models.CharField(max_length=256,null=True, blank=True )
    company_code =  models.CharField(max_length=50,null=True, blank=True)

class Investment_Files(models.Model):
    UserId =  models.IntegerField(null=True, blank=True )
    FileClose =  models.BooleanField(default=False,null=True)
    Is_Active = models.BooleanField(default=True,null=True)
    company_code =  models.CharField(max_length=50,null=True, blank=True)

class Investment_FileDetails(models.Model):
    File_Id =  models.ForeignKey(Investment_Files, on_delete=models.CASCADE,null=True, blank=True)
    BatchNo =  models.CharField(max_length=256,null=True, blank=True)
    CreatedOn = models.DateTimeField(auto_now=True, null=True, blank=True)
    company_code =  models.CharField(max_length=50,null=True, blank=True)
    Is_Active = models.BooleanField(default=True,null=True)
   
class Investment_LandlordDetails(models.Model):
    EmployeeCode = models.CharField(max_length=100,null=True,blank=True)
    LandlordName =  models.CharField(max_length=100,null=True,blank=True)
    LandlordAddress =  models.TextField(null=True, blank=True)
    LandlordPAN = models.CharField(max_length=100,null=True,blank=True)
    File_Path =  models.CharField(max_length=100,null=True,blank=True)
    FinancialYearId =  models.ForeignKey(InvestmentFinancialYear, on_delete=models.CASCADE,null=True, blank=True)
    BatchNo =  models.CharField(max_length=256,null=True, blank=True)
    CreatedOn = models.DateTimeField(auto_now=True, null=True, blank=True)
    CreatedBy = models.CharField(max_length=50,null=True,blank=True)
    company_code =  models.CharField(max_length=50,null=True, blank=True)
   

class Investment_LenderDetails(models.Model):
    InvestTypeId = models.ForeignKey(InvestmentType, on_delete=models.CASCADE,null=True, blank=True)
    EmployeeCode = models.CharField(max_length=100,null=True,blank=True)
    LenderName = models.CharField(max_length=100,null=True,blank=True)
    LenderAddress =  models.TextField(null=True, blank=True)
    LenderType = models.CharField(max_length=100,null=True,blank=True)
    LenderPAN = models.CharField(max_length=100,null=True,blank=True)
    FinancialYearId =  models.ForeignKey(InvestmentFinancialYear, on_delete=models.CASCADE,null=True, blank=True)
    CreatedOn = models.DateTimeField(auto_now=True, null=True, blank=True)
    LAmount = models.IntegerField(null=True,blank=True)
    company_code =  models.CharField(max_length=50,null=True, blank=True)


class Investment_MemberTasks(models.Model):
    BatchId =  models.IntegerField(null=True,blank=True)
    BatchNo =  models.CharField(max_length=100,null=True,blank=True)
    TaskStatus = models.IntegerField(null=True,blank=True)
    Assigning_date =  models.DateField(null=True)
    Completion_date = models.DateField(null=True)
    Assigned_By = models.CharField(max_length=100,null=True,blank=True)
    MemberCode = models.CharField(max_length=100,null=True,blank=True)
    company_code =  models.CharField(max_length=50,null=True, blank=True)
    Is_Active = models.BooleanField(default=True,null=True)

class Investment_ProofBatchMaster(models.Model):
    BatchNo = models.CharField(max_length=100,null=True,blank=True)
    NoOfProof =  models.IntegerField(null=True,blank=True)
    Is_Active = models.BooleanField(default=True,null=True)
    CreatedOn = models.DateTimeField(auto_now=True, null=True, blank=True)
    CreatedBy = models.CharField(max_length=50,null=True,blank=True)
    company_code =  models.CharField(max_length=50,null=True, blank=True)
    status = models.BigIntegerField(null=True,blank=True)
    FinancialYearId =  models.BigIntegerField(null=True,blank=True)

class ProofEntry(models.Model):
    BatchId = models.BigIntegerField(null=True,blank=True)
    BatchNo =  models.CharField(max_length=100,null=True,blank=True)
    InvestmentTypeId = models.BigIntegerField(null=True,blank=True)
    EmployeeCode =  models.CharField(max_length=100,null=True,blank=True)
    DeclaredAmount =  models.FloatField(null=True,blank=True)
    DeclaredDate =  models.DateField(null=True)
    DeclaredRemark = models.CharField(max_length=100,null=True,blank=True)
    RecievedAmount = models.FloatField(null=True,blank=True)
    RecievedDate =  models.DateField(null=True)
    RecievedRemark = models.CharField(max_length=100,null=True,blank=True)
    VerifiedAmount = models.FloatField(null=True,blank=True)
    VerifiedDate =  models.DateField(null=True)
    VerifiedRemark = models.CharField(max_length=100,null=True,blank=True)
    PolicyNumber =  models.CharField(max_length=100,null=True,blank=True)
    Period =  models.CharField(max_length=100,null=True,blank=True)
    PossessionDate =  models.DateField(null=True)
    SharePercentage = models.CharField(max_length=100,null=True,blank=True)
    MonthName = models.CharField(max_length=100,null=True,blank=True)
    Metro_NonMetro = models.IntegerField(null=True,blank=True)
    InvestmentPolicyMandatorylimit = models.CharField(max_length=100,null=True,blank=True)
    AttachmentCompulsory =  models.CharField(max_length=100,null=True,blank=True)
    Limit =  models.IntegerField(null=True,blank=True)
    LimitPanCompulsory =  models.CharField(max_length=100,null=True,blank=True)
    LimitForm =  models.CharField(max_length=100,null=True,blank=True)
    ReasonId = models.BigIntegerField(null=True,blank=True)
    FinancialYearId = models.BigIntegerField(null=True,blank=True)
    StatusId =  models.BigIntegerField(null=True,blank=True)
    File_Path =  models.CharField(max_length=100,null=True,blank=True)
    Flag = models.IntegerField(null=True,blank=True)
    OptionNo = models.BigIntegerField(null=True,blank=True)
    LandlordName = models.CharField(max_length=100,null=True,blank=True)
    LandlordAddress = models.CharField(max_length=100,null=True,blank=True)
    LandlordPan = models.CharField(max_length=100,null=True,blank=True)
    LenderName = models.CharField(max_length=100,null=True,blank=True)
    LenderAddress = models.CharField(max_length=100,null=True,blank=True)
    LenderType = models.CharField(max_length=100,null=True,blank=True)
    LenderPan = models.CharField(max_length=100,null=True,blank=True)
    LenderNameSec = models.CharField(max_length=100,null=True,blank=True)
    LenderAddressSec = models.CharField(max_length=100,null=True,blank=True)
    LenderTypeSec = models.CharField(max_length=100,null=True,blank=True)
    LenderPanSec = models.CharField(max_length=100,null=True,blank=True)
    LAmount = models.IntegerField(null=True,blank=True)
    LAmountSec = models.IntegerField(null=True,blank=True)
    UploadForm12BB =  models.TextField(null=True, blank=True)
    RentID =  models.CharField(max_length=100,null=True,blank=True)
    LoanSanctionDate =  models.CharField(max_length=100,null=True,blank=True)
    LoanNotExceed_25Lakh =  models.IntegerField(null=True,blank=True)
    PropertyNotExceed_40Lakh = models.IntegerField(null=True,blank=True)
    NotOwnHouse = models.IntegerField(null=True,blank=True)
    PropertyPurchase_Date =  models.CharField(max_length=100,null=True,blank=True)
    StampDutyNotExceed_45lakh =  models.IntegerField(null=True,blank=True)
    OtherProperty = models.IntegerField(null=True,blank=True)
    PropertyCity =  models.IntegerField(null=True,blank=True)
    NotExceed_60_90_SQ =  models.IntegerField(null=True,blank=True)
    PrevSrNo =  models.IntegerField(null=True,blank=True)
    InvoiceDate = models.DateField(null=True)
    SupplierName = models.CharField(max_length=100,null=True,blank=True)
    SupplierGSTNo = models.CharField(max_length=100,null=True,blank=True)
    GoodsPurchased =  models.BigIntegerField(null=True,blank=True)
    BaseAmt =  models.IntegerField(null=True,blank=True)
    GST_Rate =  models.IntegerField(null=True,blank=True)
    PaymentMode = models.BigIntegerField(null=True,blank=True) 
    PaymentDate = models.DateField(null=True)
    OthersIfAny =  models.CharField(max_length=100,null=True,blank=True)
    No_OfPerson = models.CharField(max_length=100,null=True,blank=True)
    VerificationAttached =  models.CharField(max_length=100,null=True,blank=True)
    DiseaseId =  models.CharField(max_length=100,null=True,blank=True)
    AttachmentPassword =  models.CharField(max_length=100,null=True,blank=True)
    AdditionalField1 = models.CharField(max_length=100,null=True,blank=True)
    AdditionalField2 = models.CharField(max_length=100,null=True,blank=True)
    AdditionalField3 = models.CharField(max_length=100,null=True,blank=True)
    AdditionalField4 = models.CharField(max_length=100,null=True,blank=True)
    AdditionalField5 = models.CharField(max_length=100,null=True,blank=True)
    AdditionalField6 = models.CharField(max_length=100,null=True,blank=True)
    Is_Active = models.BooleanField(default=True,null=True)
    company_code =  models.CharField(max_length=50,null=True, blank=True)

class ProofEntryAudit(models.Model):
    BatchId = models.BigIntegerField(null=True,blank=True)
    BatchNo =  models.CharField(max_length=100,null=True,blank=True)
    InvestmentTypeId = models.BigIntegerField(null=True,blank=True)
    EmployeeCode =  models.CharField(max_length=100,null=True,blank=True)
    DeclaredAmount =  models.FloatField(null=True,blank=True)
    DeclaredDate =  models.DateField(null=True)
    DeclaredRemark = models.CharField(max_length=100,null=True,blank=True)
    RecievedAmount = models.FloatField(null=True,blank=True)
    RecievedDate =  models.DateField(null=True)
    RecievedRemark = models.CharField(max_length=100,null=True,blank=True)
    VerifiedAmount = models.FloatField(null=True,blank=True)
    VerifiedDate =  models.DateField(null=True)
    VerifiedRemark = models.CharField(max_length=100,null=True,blank=True)
    PolicyNumber =  models.CharField(max_length=100,null=True,blank=True)
    Period =  models.CharField(max_length=100,null=True,blank=True)
    PossessionDate =  models.DateField(null=True)
    SharePercentage = models.CharField(max_length=100,null=True,blank=True)
    MonthName = models.CharField(max_length=100,null=True,blank=True)
    Metro_NonMetro = models.IntegerField(null=True,blank=True)
    InvestmentPolicyMandatorylimit = models.CharField(max_length=100,null=True,blank=True)
    AttachmentCompulsory =  models.CharField(max_length=100,null=True,blank=True)
    Limit =  models.IntegerField(null=True,blank=True)
    LimitPanCompulsory =  models.CharField(max_length=100,null=True,blank=True)
    LimitForm =  models.CharField(max_length=100,null=True,blank=True)
    ReasonId = models.BigIntegerField(null=True,blank=True)
    FinancialYearId = models.BigIntegerField(null=True,blank=True)
    StatusId =  models.BigIntegerField(null=True,blank=True)
    File_Path =  models.CharField(max_length=100,null=True,blank=True)
    Flag = models.IntegerField(null=True,blank=True)
    OptionNo = models.BigIntegerField(null=True,blank=True)
    LandlordName = models.CharField(max_length=100,null=True,blank=True)
    LandlordAddress = models.CharField(max_length=100,null=True,blank=True)
    LandlordPan = models.CharField(max_length=100,null=True,blank=True)
    LenderName = models.CharField(max_length=100,null=True,blank=True)
    LenderAddress = models.CharField(max_length=100,null=True,blank=True)
    LenderType = models.CharField(max_length=100,null=True,blank=True)
    LenderPan = models.CharField(max_length=100,null=True,blank=True)
    LenderNameSec = models.CharField(max_length=100,null=True,blank=True)
    LenderAddressSec = models.CharField(max_length=100,null=True,blank=True)
    LenderTypeSec = models.CharField(max_length=100,null=True,blank=True)
    LenderPanSec = models.CharField(max_length=100,null=True,blank=True)
    LAmount = models.IntegerField(null=True,blank=True)
    LAmountSec = models.IntegerField(null=True,blank=True)
    UploadForm12BB =  models.TextField(null=True, blank=True)
    RentID =  models.CharField(max_length=100,null=True,blank=True)
    LoanSanctionDate =  models.CharField(max_length=100,null=True,blank=True)
    LoanNotExceed_25Lakh =  models.IntegerField(null=True,blank=True)
    PropertyNotExceed_40Lakh = models.IntegerField(null=True,blank=True)
    NotOwnHouse = models.IntegerField(null=True,blank=True)
    PropertyPurchase_Date =  models.CharField(max_length=100,null=True,blank=True)
    StampDutyNotExceed_45lakh =  models.IntegerField(null=True,blank=True)
    OtherProperty = models.IntegerField(null=True,blank=True)
    PropertyCity =  models.IntegerField(null=True,blank=True)
    NotExceed_60_90_SQ =  models.IntegerField(null=True,blank=True)
    PrevSrNo =  models.IntegerField(null=True,blank=True)
    InvoiceDate = models.DateField(null=True)
    SupplierName = models.CharField(max_length=100,null=True,blank=True)
    SupplierGSTNo = models.CharField(max_length=100,null=True,blank=True)
    GoodsPurchased =  models.BigIntegerField(null=True,blank=True)
    BaseAmt =  models.IntegerField(null=True,blank=True)
    GST_Rate =  models.IntegerField(null=True,blank=True)
    PaymentMode = models.BigIntegerField(null=True,blank=True) 
    PaymentDate = models.DateField(null=True)
    OthersIfAny =  models.CharField(max_length=100,null=True,blank=True)
    No_OfPerson = models.CharField(max_length=100,null=True,blank=True)
    VerificationAttached =  models.CharField(max_length=100,null=True,blank=True)
    DiseaseId =  models.CharField(max_length=100,null=True,blank=True)
    AttachmentPassword =  models.CharField(max_length=100,null=True,blank=True)
    AdditionalField1 = models.CharField(max_length=100,null=True,blank=True)
    AdditionalField2 = models.CharField(max_length=100,null=True,blank=True)
    AdditionalField3 = models.CharField(max_length=100,null=True,blank=True)
    AdditionalField4 = models.CharField(max_length=100,null=True,blank=True)
    AdditionalField5 = models.CharField(max_length=100,null=True,blank=True)
    AdditionalField6 = models.CharField(max_length=100,null=True,blank=True)
    Is_Active = models.BooleanField(default=True,null=True)
    company_code =  models.CharField(max_length=50,null=True, blank=True)

    
class ProofStatusHistory(models.Model):
    BatchNo =  models.CharField(max_length=100,null=True,blank=True)
    EmployeeCode =  models.CharField(max_length=100,null=True,blank=True)
    company_code =  models.CharField(max_length=50,null=True, blank=True)
    Amount = models.BigIntegerField(null=True,blank=True) 
    StatusId = models.BigIntegerField(null=True,blank=True) 
    StatusColorCode =  models.CharField(max_length=100,null=True,blank=True)
    StatusIconPath =  models.CharField(max_length=100,null=True,blank=True)
    StatusDate =  models.DateField(null=True)

class RentDetails(models.Model):
    RentFrom_InvestmentTypeId = models.CharField(max_length=100,null=True,blank=True)
    RentFrom_InvestmentTypeCode = models.CharField(max_length=100,null=True,blank=True)
    RentTo_InvestmentTypeId = models.CharField(max_length=100,null=True,blank=True)
    RentTo_InvestmentTypeCode = models.CharField(max_length=100,null=True,blank=True)
    Amount = models.IntegerField(null=True,blank=True)
    FinYearId = models.IntegerField(null=True,blank=True)
    Is_Active = models.BooleanField(default=True,null=True)
    CreatedOn = models.DateTimeField(auto_now=True, null=True, blank=True)
    UpdatedOn = models.DateTimeField(auto_now=True, null=True, blank=True)
    company_code =  models.CharField(max_length=50,null=True, blank=True)


class ClaimDeductionQuestions(models.Model):
    Question =  models.CharField(max_length=256,null=True, blank=True)
    InvestmentTypeId =  models.IntegerField(null=True,blank=True)
    Is_Active = models.BooleanField(default=True,null=True)
    ParentId =  models.IntegerField(null=True,blank=True)
    QuestionType = models.CharField(max_length=256,null=True, blank=True)
    Invest_Type_Code = models.CharField(max_length=256,null=True, blank=True)
    UpdatedBy = models.CharField(max_length=50,null=True,blank=True)
    PopUpMsg = models.CharField(max_length=50,null=True,blank=True)
    company_code  = models.CharField(max_length=50,null=True, blank=True)

class FieldType(models.Model):
    name = models.CharField(max_length=256,null=True, blank=True)
    Is_Active = models.BooleanField(default=True,null=True)

class Configuration(models.Model):
    Is_Active = models.BooleanField(default=True,null=True)
    sectionId = models.ForeignKey(Section, on_delete=models.CASCADE,null=True, blank=True)
    invTypeId = models.ForeignKey(InvestmentType, on_delete=models.CASCADE,null=True, blank=True)
    policyNo = models.CharField(max_length=50,null=True, blank=True)
    policyNocheck = models.BooleanField(null=True, blank=True)
    receiptNo = models.CharField(max_length=50,null=True, blank=True)
    receiptNocheck = models.BooleanField(null=True, blank=True)
    periodcheck = models.BooleanField(null=True, blank=True)
    possessiondatecheck = models.BooleanField(null=True, blank=True)
    possessiondate = models.DateField(null=True)
    fieldtype = models.CharField(max_length=50,null=True, blank=True)
    formula = models.CharField(max_length=150,null=True, blank=True)
    sharepercentagecheck = models.BooleanField(null=True, blank=True)
    metro_nonmetrocheck = models.BooleanField(null=True, blank=True)
    lenderform = models.BooleanField(null=True, blank=True)
    IsPreviousYear = models.BooleanField(null=True, blank=True)
    limitpancomp = models.BooleanField(null=True, blank=True)
    limitpanamount = models.CharField(max_length=50,null=True, blank=True)
    block_maxlimit = models.BooleanField(null=True, blank=True)
    maxlimit = models.CharField(max_length=50,null=True, blank=True)
    replaceamount = models.CharField(max_length=50,null=True, blank=True)
    lendertype = models.CharField(max_length=250,null=True, blank=True)
    ltapayment = models.BooleanField(null=True, blank=True)
    

