# Generated by Django 4.2.7 on 2025-02-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shiftmanagers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeId', models.CharField(max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(max_length=10, null=True)),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shiftswap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeId', models.CharField(max_length=150, null=True)),
                ('AttendanceId', models.CharField(max_length=100, null=True)),
                ('Shiftdate', models.DateField(null=True)),
                ('ShiftId', models.IntegerField(null=True)),
                ('Shiftname', models.CharField(max_length=50, null=True)),
                ('Reason', models.TextField(blank=True, null=True)),
                ('SwapempId', models.CharField(max_length=100, null=True)),
                ('Swapshiftdate', models.DateField(null=True)),
                ('SwapShiftId', models.IntegerField(null=True)),
                ('Swapshiftname', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('Status', models.CharField(max_length=100, null=True)),
                ('created_by', models.CharField(max_length=10, null=True)),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftswapAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RequestId', models.IntegerField(null=True)),
                ('ActionTaken', models.CharField(default='Pending', max_length=50, null=True)),
                ('ManagerId', models.CharField(max_length=100, null=True)),
                ('RejectionReason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(max_length=10, null=True)),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
    ]
